name: Music Alias Resolver
guid: 1f2651b1-0793-4504-b1b1-5e4de18ba892
version: 0.1.0.0
targetAbi: 10.11.0.0
framework: net9.0
overview: Gets english name for music.
description: |
  Checks if Albums, Tracks, and Artists have english aliases.
category: General
owner: Bobthesponge10
artifacts:
  - Jellyfin.Plugin.AliasResolver.dll
  - IpaDic/char.bin
  - IpaDic/matrix.bin
  - IpaDic/sys.dic
  - IpaDic/unk.dic
changelog: Initial Release
